# Generated by Django 5.1.3 on 2024-11-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, help_text='Temporary OTP for email verification', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the OTP was created', null=True),
        ),
    ]
