# Generated by Django 5.1.3 on 2024-11-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_user_otp_code_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, help_text='Token for password reset', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_expiration',
            field=models.DateTimeField(blank=True, help_text='Expiration time for the reset token', null=True),
        ),
    ]
