# Generated by Django 5.1.3 on 2024-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0003_user_reset_token_user_reset_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Indicates if the user is blocked by an admin'),
        ),
    ]
