# Generated by Django 5.1.3 on 2024-12-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='about',
            field=models.TextField(blank=True, help_text='Discription about the tags'),
        ),
    ]
