# Generated by Django 5.1.3 on 2025-01-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='connection_count',
            field=models.IntegerField(default=0),
        ),
    ]
