# Generated by Django 5.1.3 on 2025-01-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0012_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_time',
            field=models.PositiveIntegerField(default=0, help_text="User's available time balance in minutes"),
        ),
        migrations.AddField(
            model_name='user',
            name='held_time',
            field=models.PositiveIntegerField(default=0, help_text="User's time currently on hold for pending requests"),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('request', 'teacher')},
        ),
    ]
