# Generated by Django 5.1.3 on 2025-01-15 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0014_remove_skillsharingrequest_requested_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='scheduled_at',
            new_name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='timetransaction',
            name='related_schedule',
        ),
        migrations.RemoveField(
            model_name='timetransaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='timetransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='timetransaction',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetransaction',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.schedule'),
        ),
        migrations.AddField(
            model_name='timetransaction',
            name='to_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='time_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('PR', 'Proposed'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='timetransaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
