# Generated by Django 5.1.3 on 2025-02-02 11:53

import cloudinary.models
import django.core.validators
import user_side.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0017_timeplan_timeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile image of the user (max 5MB)', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), user_side.models.validate_image_size], verbose_name='profile_image'),
        ),
    ]
