# Generated by Django 5.1.3 on 2025-02-02 12:48

import cloudinary.models
import django.core.validators
import user_side.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0018_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Featured image for the blog post (max 5MB)', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), user_side.models.validate_image_size], verbose_name='blog_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Banner image for the user profile page (max 5MB)', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), user_side.models.validate_image_size], verbose_name='banner_image'),
        ),
    ]
